import {
  ShoppingCart,
  ShoppingBag,
  UtensilsCrossed,
  Home,
  Car,
  Bus,
  Plane,
  BriefcaseBusiness,
  GraduationCap,
  Heart,
  Activity,
  Smartphone,
  Laptop,
  Tv,
  Music,
  Gamepad2,
  Gift,
  Coffee,
  CreditCard,
  Banknote,
  PiggyBank,
  Landmark,
  Star,
  Flag,
  Tag,
  type LucideIcon,
} from 'lucide-react';

export const ICONS: { name: string; Icon: LucideIcon }[] = [
  { name: 'ShoppingCart', Icon: ShoppingCart },
  { name: 'ShoppingBag', Icon: ShoppingBag },
  { name: 'UtensilsCrossed', Icon: UtensilsCrossed },
  { name: 'Home', Icon: Home },
  { name: 'Car', Icon: Car },
  { name: 'Bus', Icon: Bus },
  { name: 'Plane', Icon: Plane },
  { name: 'BriefcaseBusiness', Icon: BriefcaseBusiness },
  { name: 'GraduationCap', Icon: GraduationCap },
  { name: 'Heart', Icon: Heart },
  { name: 'Activity', Icon: Activity },
  { name: 'Smartphone', Icon: Smartphone },
  { name: 'Laptop', Icon: Laptop },
  { name: 'Tv', Icon: Tv },
  { name: 'Music', Icon: Music },
  { name: 'Gamepad2', Icon: Gamepad2 },
  { name: 'Gift', Icon: Gift },
  { name: 'Coffee', Icon: Coffee },
  { name: 'CreditCard', Icon: CreditCard },
  { name: 'Banknote', Icon: Banknote },
  { name: 'PiggyBank', Icon: PiggyBank },
  { name: 'Landmark', Icon: Landmark },
  { name: 'Star', Icon: Star },
  { name: 'Flag', Icon: Flag },
  { name: 'Tag', Icon: Tag },
];

export function getIcon(name: string): LucideIcon | undefined {
  return ICONS.find((icon) => icon.name === name)?.Icon;
}
